(function(g){var window=this;'use strict';var Egb=function(a,b,c){g.J(function(d){a.B=g.ds(b,c);g.va(d)})},D3=function(a){a.isActive()||a.start()},Fgb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Ggb=function(a){return g.gQ(a)||a.L("web_enable_caption_language_preference_stickiness")},Hgb=function(a,b){var c=new g.xQ;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Igb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.G(f,g.Pu(),2);if(f.j!=3){d=f.B;if(!d)throw g.bu("gct");return g.G(f,g.PQ(d),3)}e=f.B;return f.return(e.get("captions",c))})},Jgb=function(a,b,c){Igb(a,b).then(function(d){d&&c(d.trackData,new g.xQ(d.metadata))})},Mgb=function(a){if(!Kgb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(Lgb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Ngb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.pdb?g.pdb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={vG:c.vG};c.vG=d;var e=function(f){return function(){return String(a[f.vG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.vG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.vG,"gi"),e)}return b},Ogb=function(){return g.mt("yt-player-caption-display-settings")},E3=function(){this.segments=[]},Pgb=function(a,b){var c=g.fc(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Xb(a.segments,c),g.Xb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.dc(a.segments,c,0,b),g.dc(a.segments,c+1,0,b)))},Qgb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.oa=c;this.Z=d;this.G=e;this.W=f;this.D=new E3;this.K=-1;this.C=this.B=this.j=null;this.qa=0;this.N=new g.Ep(this.E_,1E3,this);this.events=new g.kG(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.YB);this.YB();this.E_()},Rgb=function(a){return a.j&&a.j.Rf?a.j.Rf+a.player.Nc()<a.player.getCurrentTime():!1},Sgb=function(a,b){if(a.policy.Am&&a.player.Au()){var c=g.QN(b,a.policy,{});
c.set("pot",a.player.Au());c=c.le()}else c=g.QN(b,a.policy,{}).le();var d={format:"RAW",withCredentials:!0};if(a.policy.Ia){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.PB(e,g.aM):d.postBody=(0,g.cU)([120,0])}a.G&&(d.responseType="arraybuffer");var f=++a.qa,h=(0,g.hu)();a.C=g.hs(c,d,3,100).then(function(l){if(a.policy.uG&&f%100===1){var m=(0,g.hu)();a.player.ma("caprsp",{rn:f,ms:m-h,kb:(l.xhr.responseText.length/1024).toFixed()})}a:{l=l.xhr;a.Ja();if(a.B){var n=!(a.G?l.response:
l.responseText)||l.status>=400;if(m=g.yFa(l)){l=g.QN(a.B,a.policy,{});a.B.Jk(l,m);Sgb(a,a.B);break a}n?a.player.ma("capfail",{status:l.status}):(a.player.Lh().yg("fcb_r"),m=a.B.ib[0].Ma,a.Z!=null&&a.K!==m&&(n=a.B.ib[0],a.G?a.Z(l.response,(n.startTime+a.player.Nc())*1E3):a.Z(l.responseText,(n.startTime+a.player.Nc())*1E3),a.K=m))}a.B=null;a.C=null}}).al(function(l){a.B=null;
a.C=null;var m;a.player.ma("capfail",{rn:f,status:(m=l.xhr)==null?void 0:m.status})});
a.B=b;Pgb(a.D,a.B.ib[0].Ma)},F3=function(a,b){g.mY.call(this,b);
this.B=a;this.J=b;this.C=null;this.K=!1;this.N=g.fE(this.J.U())&&!this.B.isManifestless},mhb=function(a,b){var c=[],d;
for(d in a.B.j)if(a.B.j.hasOwnProperty(d)){var e=a.B.j[d];if(g.S0a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Geb.get(e);q==null&&(q=Tgb[e]||Tgb[e.replace(/-/g,"_")],g.Geb.set(e,q));h=q||h}c.push(new g.xQ({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
nhb=function(a,b){return b!=null&&b in a.B.j?a.B.j[b]:null},ohb=function(a,b,c){var d=[],e;
for(e in a.B.j)if(a.B.j.hasOwnProperty(e)){var f=a.B.j[e];if(g.S0a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},G3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Te);a.params.Te&&Object.assign(r,a.params.Te);Object.assign(r,c.Te);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Te=r;var t=q.Vi===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,A,C;(l=l.bb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":Ngb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.S.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var E=
this;this.K=[];this.Fa=!1;this.B=a;this.Ia=this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.wc=c;this.qa=b;this.D=this.Da("captions-text");this.Qb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ua=phb(d,e,f,h);this.pc=m;l&&(this.G=this.Da("caption-edit"),this.T(this.G,"click",function(){E.pc()}));
this.type=0;this.Wa=this.Ua*qhb(r);this.Eb=p;a=new g.MX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.e5,this);a.subscribe("dragmove",this.d5,this);a.subscribe("dragend",this.c5,this);this.fb=this.Ya=this.sb=this.qb=0;a="";this.j.windowOpacity&&(a=Mgb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":rhb[this.j.textAlign]};this.Qb&&(b["border-radius"]=a?this.Wa/8+"px":"");(this.C=
this.B.params.Vi===2||this.B.params.Vi===3)&&shb(this,this.element);g.Fm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Om){case 0:case 1:case 2:g.Mp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Mp(this.element,"ytp-caption-window-bottom")}},shb=function(a,b){var c="vertical-rl";
a.j.LU===1&&(c="vertical-lr");g.Hm&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.Fm(b,"-o-writing-mode",c);g.Fm(b,"-webkit-writing-mode",c);g.Fm(b,"writing-mode",c);g.Fm(b,"text-orientation","upright");g.Mp(b,"ytp-vertical-caption");a.B.params.Vi===3&&(g.Fm(b,"text-orientation",""),g.Fm(b,"transform","rotate(180deg)"))},qhb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},thb=function(a,b){var c={},d=b.background?b.background:a.j.Te.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Te.backgroundOpacity;d=Mgb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Qb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Ua*qhb(b)+"px";d=1;e=b.color||a.j.Te.color;if(b.color||b.textOpacity!=null)e=Mgb(e),d=b.textOpacity==null?a.j.Te.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.iP&&(h=e=b.iP);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ws()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Te.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.x$&&(c.visibility="hidden");b.NZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.jQ||g.$t,a.B.params.Vi===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.Ap===1||b.Ap===2||b.Ap===3||b.Ap===4||b.Ap===5)if(g.jQ)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ap){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},H3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},uhb=function(a){a.N=g.qh("SPAN");
g.Fm(a.N,{display:"block"});g.Mp(a.N,"caption-visual-line");a.D.appendChild(a.N)},vhb=function(a,b){var c=g.qh("SPAN");
g.Fm(c,{display:"inline-block","white-space":"pre-wrap"});g.Fm(c,thb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Fm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Fm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},whb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Te);Object.assign(d,c||b.j);Object.assign(d,a.wc.Te);(c=!a.N)&&uhb(a);for(var e=a.Ka&&a.Ia&&g.Xg(d,a.Ia)?a.Ka:vhb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(uhb(a),e=vhb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.rh(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.jQ||!g.Im(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Im(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.mh?g.Fm(e,m,"1em"):g.Fm(e,m,"0.5em")))}a.Ia=d;a.Ka=e;a.K.push(b)},phb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},yhb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new xhb(this);this.G=new xhb(this);this.j=[];this.clear()},Ahb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{gx:a,
St:b,result:0};a=zhb[a];b=zhb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.ye()&&c.St===d;if(d)return{gx:a,St:b,result:1}}else if(b&128&&1<=a&&a<=31)return{gx:a,St:b,result:2};return{gx:a,St:b,result:3}},Chb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Bhb(a.D,b,c,d))},Dhb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?Chb(a,d.SX,d.TX,b):d.type===1&&a.B&496&&Bhb(a.G,d.SX,d.TX,b);a.j.length=0},I3=function(){this.type=0},J3=function(){this.state=this.St=this.gx=0},Ehb=function(){this.timestamp=this.j=0},K3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new I3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Ehb}},L3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Jhb=function(a,b){switch(a){case 0:return Fhb[(b&127)-32];
case 1:return Ghb[b&15];case 2:return Hhb[b&31];case 3:return Ihb[b&31]}return 0},M3=function(a){return a.B[a.row][a.col]},N3=function(a,b,c){b>=2&&a.col>1&&(--a.col,M3(a).j=0);
var d=M3(a);d.timestamp=a.D.time+0;d.j=Jhb(b,c);a.col<32&&a.col++},Khb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},O3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},Lhb=function(a){a.row=a.j>0?a.j:1;
a.col=1;O3(a,0,15)},Mhb=function(a){this.C=a;
this.G=0;this.style=new I3;this.K=new K3(this.C);this.N=new K3(this.C);this.text=new K3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Nhb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(L3(d,c),Lhb(a.B),Lhb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(L3(d,c),O3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Ohb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Phb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},xhb=function(a){this.j=a;
this.G=0;this.C=new Mhb(this.j);this.K=new Mhb(this.j);this.B=new J3;this.D=this.C},Bhb=function(a,b,c,d){a.B.update();
b=Ahb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.gx;c=b.St;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&N3(a,0,b),c&96&&N3(a,0,c),b!==0&&c!==0&&a.style.type===3&&L3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.gx=e,b.St=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Khb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));O3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:N3(b.j,0,32);break a;case 48:c===57?(d=b.j,M3(d).j=0,d.col<32&&d.col++):N3(b.j,1,c&15)}break;case 2:c&32&&N3(b.j,2,c&31);break;case 3:c&32&&N3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:Ohb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,M3(d).j=0);break;case 36:d=b.j;b=M3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:Nhb(b,2,d);break;case 38:Nhb(b,3,d);break;case 39:Nhb(b,4,d);break;case 40:N3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Lhb(d);Phb(b);break;case 43:Phb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:L3(a,
d)}O3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;L3(a,d);Khb(a,b,b+1,a.j-1);O3(a,a.row,1)}break;case 46:O3(b.D,0,15);break;case 47:L3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Ohb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},Qhb=function(){},P3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.KE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Shb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.gg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Rhb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new P3(a,b,e,c,l,d,m)}switch(m.gg){case 9:case 10:m.Ap=1;break;case 11:m.Ap=2;break;case 12:m.Ap=3;break;case 13:m.Ap=4;break;case 14:m.Ap=5}return new P3(a,b,e,c,l.textContent||"",d,m)},Rhb=function(a,b,c,d,e){var f=g.ws(),h=
f?g.qh("DIV"):g.qh("RUBY"),l=g.qh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.qh("DIV"):g.qh("RP");a.textContent=b;h.appendChild(a);b=f?g.qh("DIV"):g.qh("RT");b.textContent=c;h.appendChild(b);c=e.gg;if(c===10||c===11||c===12||c===13||c===14)if(g.Fm(b,"text-emphasis-style","filled circle"),g.Fm(b,"text-emphasis-color","currentcolor"),g.Fm(b,"webkit-text-emphasis","filled circle"),e.gg===11||e.gg===13)g.Fm(b,"webkit-text-emphasis-position","under left"),g.Fm(b,"text-emphasis-position","under left");c=!0;if(e.gg===4||e.gg===7||e.gg===12||
e.gg===14)g.Fm(h,"ruby-position","over"),g.Fm(h,"-webkit-ruby-position","before");else if(e.gg===5||e.gg===6||e.gg===11||e.gg===13)g.Fm(h,"ruby-position","under"),g.Fm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.qh("DIV"):g.qh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Fm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Fm(f,"display","none"),f=f.nextElementSibling,g.Fm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Fm(h.lastElementChild,"display","none"),d?(g.Fm(h,"padding-top","0.6em"),g.Fm(f,"top","0")):(g.Fm(h,"padding-bottom","0.6em"),g.Fm(f,"bottom","0")));return h},Q3=function(){g.O.apply(this,arguments)},R3=function(a,b,c,d,e){g.KE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Thb=function(a){var b="_"+S3++;
return new R3(0,0x8000000000000,0,b,a)},T3=function(a){Q3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+S3++;this.K={};this.B=this.j=null;this.G=!0},U3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},V3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},W3=function(a,b){a=U3(a,b);
return a!==void 0?a:null},Y3=function(a,b){a=a.getAttribute(b);
if(a!=null)return X3.test(a),a},Uhb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=W3(b,"mh");a!=null&&(c.NB=a);a=W3(b,"ju");a!=null&&(c.textAlign=a);a=W3(b,"pd");a!=null&&(c.Vi=a);a=W3(b,"sd");a!=null&&(c.LU=a);a=Y3(b,"wfc");a!=null&&(c.windowColor=a);b=U3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},Vhb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=W3(b,"ap");a!=null&&(c.Om=a);a=U3(b,"cc");a!=null&&(c.Vt=a);a=U3(b,"ah");a!=null&&(c.Mk=a);a=U3(b,"rc");a!=null&&(c.Rs=a);b=U3(b,"av");b!=null&&(c.Dp=b);return c},Whb=function(a,b,c,d){var e={};
Object.assign(e,Vhb(a,b));Object.assign(e,Uhb(a,b));d?g.Xg(e,a.C)?(d=a.D,e=a.C):d="_"+S3++:d=b.getAttribute("id")||"_"+S3++;a=U3(b,"t")+c;b=U3(b,"d")||0x8000000000000;if(e.Vi===2||e.Vi===3)c=e.Rs,e.Rs=e.Vt,e.Vt=c;return new R3(a,b,0,d,e)},Z3=function(a){Q3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},$3=function(a){a=g.Bg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Xhb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Rs=a);b=b.ccColCount;b!==void 0&&(f.Vt=b);if(f.Vi===2||f.Vi===3)b=f.Rs,f.Rs=f.Vt,f.Vt=b;return new R3(c,d,0,e,f)},a4=function(a,b,c){g.mY.call(this,a);
this.videoData=b;this.audioTrack=c;this.G=b.Lw},b4=function(a,b,c,d,e,f,h,l,m,n){G3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},c4=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.B=[];this.j=new DataView(this.trackData)},d4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},e4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},f4=function(a,b){Q3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new yhb;this.j.B=1<<this.track},Zhb=function(a){if(typeof a==="string")return!1;
a=new c4(a,8,0);return Yhb(a)},Yhb=function(a){if(!(a.byteOffset<a.j.byteLength)||e4(a)!==1380139777)return!1;
a.version=d4(a);if(a.version>1)return!1;d4(a);d4(a);d4(a);return!0},g4=function(a,b,c,d,e,f,h,l,m,n){G3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Aa=[];this.oa=this.W=this.Oa=0;this.Ca=NaN;this.Hb=0;this.Sb=null;this.Ta=new g.Ep(this.yca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.MX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Mp(this.element,"ytp-caption-window-rollup");g.P(this,this.Ta);g.Fm(this.element,"overflow","hidden")},$hb=function(a,b){if(!b)return"";
a.C&&a.B.params.LU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},aib=function(a){a.Aa=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Rs,c=0,d=0,e=a.Aa.length-1;c<b&&e>-1;){var f=a.Aa[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ca)&&((d=a.j.Vt)?(e=g.qh("SPAN"),g.xh(e,"\u2013".repeat(d)),g.Fm(e,thb(a,a.j.Te)),a.D.appendChild(e),a.Ca=e.offsetWidth,a.D.removeChild(e)):a.Ca=0);d=a.D;a.oa=c.call(b,a.Ca,a.Hb,(a.C?d.offsetHeight:d.offsetWidth)+1)},bib=function(a,b){aib(a);
var c=a.Aa.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Oa){var d=c>0&&a.Oa===0,e=c<a.Oa;b||isNaN(c)||d||!e||(g.Mp(a.element,"ytp-rollup-mode"),g.Fp(a.Ta));g.Fm(a.D,"transform",$hb(a,c));a.Oa=c}aib(a)},h4=function(){Q3.call(this)},cib=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new P3(b,c,d,e.id,p.nodeValue,f||n>0,g.Vg(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);cib(a,b,c,d,e,!0,p,q,m)}}},dib=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},eib=function(a,b,c,d){d=Object.assign({NB:0},d);
return new R3(a,b,c,"_"+S3++,d)},i4=function(a,b){g.O.call(this);
this.J=a;this.Y=b;this.j=null;this.B=this.J.SA();this.logger=new g.PT("caps")},fib=function(a){if(typeof a==="string"||Zhb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.UM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.tB(a)},hib=function(a,b,c){if(typeof b==="string"||Zhb(b))return[{trackData:b,
FU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.xEa(d);if(a.B&&e){var f=g.pEa(e),h=g.qEa(e);e=e.tj;f&&e&&a.B.zI(e,f,h)}a=g.cN(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.tB(e),f.push({trackData:e,FU:c+h*1E3});gib(d,f,c);return f=f.filter(function(l){return!!l.trackData})},gib=function(a,b,c){var d=g.UM(a,0,1836476516),e=9E4;
d&&(e=g.VM(d)||9E4);d=0;for(var f=g.cN(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.UM(a,l.dataOffset,1953653094))&&(l=g.UM(a,l.dataOffset,1952867444))&&(l=g.aN(l)/e*1E3,h===0&&(d=l),b[h].FU=l-d+c||c*h*1E3)}},iib=function(a,b,c,d,e){if(!Zhb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new f4(e,b));return a.j.jp(c,d)},jib=function(a,b,c){a.j||(a.j=new h4);
a=a.j.jp(b,c);Math.random()<.01&&g.qx(Error("Deprecated subtitles format in web player: WebVTT"));return a},lib=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new Z3(kib(b))),a.j.jp(c,d)}catch(f){return g.px(f),[]}var e=g.q1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new T3(kib(b),a.Y)),a.j.jp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},kib=function(a){var b=
{};
if(a=g.AQ(a))b.lang=a,g.acb.test(a)&&(b.Vi=1);return b},j4=function(a){g.kY.call(this,a);
var b=this;this.J=a;this.Fa=[];this.qa={};this.Ua={};this.N=!1;this.B=this.j=this.Z=this.W=this.Oa=this.qb=null;this.Y=this.J.U();this.videoData=this.J.getVideoData();this.sb=this.J.ob();var c;this.fb=(c=this.J.getVideoData(1))==null?void 0:g.oR(c);this.C={Te:{}};this.G={Te:{}};this.Qb=g.TR(this.videoData);this.Ya=g.T0a(this.videoData,this.J);this.Hb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.De;this.Ta=this.Y.controlsType==="3";this.Wa=new i4(this.J,this.Y);this.Aa=new g.kG(this);
this.K=new g.S({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.oa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.oq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.fq(d));this.storage=c;var e;this.Ib=!((e=a.Fe())==null||!e.pI());this.D=mib(this);this.Ca=!this.D&&this.Ta&&this.Ib&&this.Ya;g.P(this,this.Wa);this.D?this.Ia=this.Ka=null:(this.Ka=new g.Dp(this.XU,void 0,this),g.P(this,this.Ka),this.Ia=new g.Ep(this.gea,2E3,this),g.P(this,
this.Ia));g.P(this,this.Aa);g.vS(this.player,this.K.element,4);g.P(this,this.K);this.D||this.Aa.T(a,"resize",this.ZU);(this.Eb=g.RP(this.Y)&&!g.Ws()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.Aa.T(a,"resize",this.Hba);this.Aa.T(a,"onPlaybackAudioChange",this.Taa);this.Aa.T(a,g.ME("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.T(a,g.NE("captions"),function(f){b.onCueRangeExit(f)});
this.fb&&this.Aa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
nib(this,Ogb()||{});this.player.Dd("onCaptionsModuleAvailable")},qib=function(a){if(a.Y.Ib===1||a.videoData.xD===1||g.CR(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.Y.Ib===2){if(g.gQ(a.Y))var c=oib(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=Fgb(a.player.getAudioTrack(),g.gQ(a.Y));var d=g.CR(a.videoData,"yt:cc");if(pib(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.CR(a.videoData,
"yt:cc")==="on"},k4=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},pib=function(a){var b=void 0,c=g.ut(g.tt(),65);
if(g.gQ(a.Y)&&c!=null){if(oib(a)!=null)return!1;b=!c}return b},rib=function(a){var b;
a.Qb?b=new a4(a.player,a.videoData,a.getAudioTrack()):a.Ya?b=new F3(a.videoData.j,a.player):a.Hb?b=new g.nY(a.player,a.videoData,a.getAudioTrack()):b=new g.oY(a.player,a.videoData.De,a.videoData.videoId,g.EMa(a.videoData),a.videoData.Tn,a.videoData.eventId);return b},m4=function(a,b){if(a.j){if(a.Z&&a.Z.D)return a.Z.D;
g.OR(a.videoData)&&(b=!0);b||(b=a.Sb?!1:a.Hb?!1:!0);b=b||sib(a);b=g.$X(a.j.j,b);var c=null;if(Ggb(a.Y)){var d=a.J.isInline()?void 0:g.mt("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.CR(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.AQ(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.AQ(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.CR(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.AQ(b[f])===d[e])return b[f];d=null;a.Z&&a.Z.C&&(d=a.Z.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||l4(a));d&&c&&g.AQ(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Hgb(d,c));return d}return null},l4=function(a){return a.Z&&a.Z.j},n4=function(a){var b=l4(a);
return!!b&&a.B===b},tib=function(a){var b=Fgb(a.player.getAudioTrack(),g.gQ(a.Y)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=m4(a,a.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&k4(a)?c=l4(a):pib(a)||a.N||qib(a)?c=m4(a,a.N):k4(a)&&(c=l4(a));if(a.D||a.Ca){var d=g.$X(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.qh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.yQ(f));h.setAttribute("srclang",g.AQ(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Mx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Fe();c.IE(b);c=
c.Jb();a.Ib&&a.Aa.T(c.textTracks,"change",a.gda)}else!a.B&&c&&o4(a,c),a.player.Dd("onCaptionsTrackListChanged"),a.player.sf("onApiChange")},uib=function(a,b){var c=a.J.Fe().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},o4=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.N=c,a.N&&(g.gQ(a.Y)?p4(a,!!b):q4(a,!!b)));a.Y.L("html5_report_caption_format_change")&&vib(a,a.B,b,a.N,!1);a.B=b;k4(a)&&(b=l4(a),a.Y.L("html5_report_caption_format_change")&&vib(a,a.B,b,a.N,!0),a.B=b);var d;wib(a,(d=a.B)!=null?d:void 0);a.load()},yib=function(a,b){if(b instanceof R3){var c=a.qa[b.id];
c&&c.B!==b&&(c.dispose(),delete a.qa[b.id],c=null);c||(c=xib(a,b))&&(a.qa[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},xib=function(a,b){var c=zib(a);
if(!c)return null;var d=a.B?g.AQ(a.B):null;d&&g.acb.test(d)&&(b.params.Vi=1);var e=a.sb.getPlayerSize();d=e.height*a.oa.height;e=e.width*a.oa.width;a.Y.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.NB!=null?b.params.NB:b.j.length>1?1:0){case 1:return new b4(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.SN.bind(a),a.J);case 2:return new g4(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.SN.bind(a),a.J);default:return new G3(b,a.C,a.G,c.width,c.height,e,
d,a.Y.experiments,a.SN.bind(a),a.J)}},nib=function(a,b,c){c=c===void 0?!1:c;
var d=r4.Te;a.C={};Object.assign(a.C,r4);a.C.Te={};Object.assign(a.C.Te,d);a.G={Te:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;X3.test(f);e.Te.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;X3.test(f);e.Te.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||r4.windowColor;X3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Te.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Te.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Te;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Te.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=r4.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Te.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Te.fontFamily=f;a.loaded&&a.ZU();c&&g.lt("yt-player-caption-display-settings",b,2592E3)},Bib=function(a,b,c){b&&!a.W?(b=Thb({Vi:0,
lang:"pl"}),a.W=[b,new P3(b.start,b.end-b.start,0,b.id,c!=null?c:"Napisy b\u0119d\u0105 wygl\u0105da\u0142y tak")],a.player.bf(a.W)):!b&&a.W&&(Aib(a,a.W),a.W=null)},Aib=function(a,b){a.player.hm(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Yb(a.Fa,c.value);D3(a.Ka)},wib=function(a,b){a.Y.L("html5_modify_caption_vss_logging")&&(a.videoData.rE=b)},zib=function(a){var b=a.sb.getVideoContentRect(!0).height,c=a.sb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.oa.height;c*=a.oa.width;return{width:c,height:b}},q4=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},p4=function(a,b){a.J.isInline()||g.lt("yt-player-sticky-caption",b,2592E3)},oib=function(a){if(!a.J.isInline())return g.mt("yt-player-sticky-caption")},mib=function(a){var b,c=!((b=a.J.Fe())==null||!b.oI());
return a.Ta&&c&&!a.Ya},sib=function(a){return a.Y.L("web_deprecate_always_includes_asr_setting")&&g.gQ(a.Y)?!0:!!g.ut(g.tt(),66)},vib=function(a,b,c,d,e){e?a.rj(c,!0,"g"):d?b?a.rj(c,!!c,"m"):c&&a.rj(c,!0,"m"):!b&&c&&a.rj(c,!0,"s")};
g.mY.prototype.vT=g.da(55,function(){return!1});
g.mY.prototype.Xu=g.da(54,function(){});
g.nY.prototype.Xu=g.da(53,function(a,b,c){var d=this;this.Ja();b=this.Mx(a,b);var e=this.Pa.U().L("html5_report_captions_ctmp_qoe"),f=(0,g.hu)();this.At();Egb(this,b,{format:"RAW",onSuccess:function(h){d.B=null;if(e){var l=(h.responseText.length/1024).toFixed(),m=(0,g.hu)();d.videoData.ma("capresp",{ms:m-f,kb:l})}c(h.responseText,a)},
onError:e?function(h){var l;h=(l=h==null?void 0:h.status)!=null?l:0;d.videoData.ma("capfail",{status:h})}:void 0,
withCredentials:!0})});
g.oY.prototype.Xu=g.da(52,function(a,b,c){var d=this;this.Ja();b=this.Mx(a,b);this.At();this.B=g.ds(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.UX.prototype.pA=g.da(51,function(){for(var a=g.ih(document,"track",void 0,this.j),b=0;b<a.length;b++)g.vh(a[b])});
g.q_.prototype.pA=g.da(50,function(){this.mediaElement.pA()});
g.UX.prototype.pI=g.da(49,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.q_.prototype.pI=g.da(48,function(){return this.mediaElement.pI()});
g.UX.prototype.oI=g.da(47,function(){return!!this.j.textTracks});
g.q_.prototype.oI=g.da(46,function(){return this.mediaElement.oI()});
g.UX.prototype.IE=g.da(45,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.q_.prototype.IE=g.da(44,function(a){this.mediaElement.IE(a)});
g.UV.prototype.zI=g.da(40,function(a,b,c){this.Zc.zI(a,b,c)});
g.z_.prototype.zI=g.da(39,function(a,b,c){this.Ka.set(a,{au:b,cA:c})});
g.UV.prototype.JF=g.da(38,function(a){return this.Zc.JF(a)});
g.z_.prototype.JF=g.da(37,function(a){var b=2;this.K.has(a)?b=0:g.B6a(this,a)&&(b=1);return b});
g.PT.prototype.j=g.da(36,function(a){g.ZOa.apply(null,[6,this.tag,a].concat(g.x(g.Ea.apply(1,arguments))))});
g.oS.prototype.Xk=g.da(34,function(a,b){var c=g.iS(this.app);c&&c.Xk(a,b)});
g.lW.prototype.Xk=g.da(33,function(a,b){a=[a,b];g.kW(this,g.SK(this.provider),"cfi",a)});
g.zW.prototype.Xk=g.da(32,function(a,b){this.qoe&&this.qoe.Xk(a,b)});
g.$W.prototype.Xk=g.da(31,function(a,b){this.Tb().Xk(a,b)});
g.oS.prototype.rj=g.da(30,function(a,b,c){var d=g.iS(this.app);d&&d.rj(a,b,c)});
g.lW.prototype.rj=g.da(29,function(a,b,c){b=[a,b,this.Sb,c];g.kW(this,g.SK(this.provider),"cfs",b);this.Sb=a});
g.zW.prototype.rj=g.da(28,function(a,b,c){this.qoe&&this.qoe.rj(a,b,c)});
g.$W.prototype.rj=g.da(27,function(a,b,c){this.Tb().rj(a,b,c)});
g.PV.prototype.XF=g.da(18,function(){return this.N});
g.X_.prototype.XF=g.da(17,function(){var a;return((a=g.iS(this))==null?void 0:a.SA())||null});
g.oS.prototype.SA=g.da(16,function(){return this.app.XF()});
g.$W.prototype.SA=g.da(15,function(){var a;return((a=this.ra)==null?void 0:a.XF())||null});
g.GM.prototype.FK=g.da(1,function(a){return(a=this.Bo(a))?a.j:0});
g.fO.prototype.FK=g.da(0,function(){return 0});
var Lgb=/#(.)(.)(.)/,Kgb=/^#(?:[0-9a-f]{3}){1,2}$/i,Tgb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
E3.prototype.contains=function(a){a=g.fc(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
E3.prototype.length=function(){return this.segments.length/2};
g.z(Qgb,g.O);g.k=Qgb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.YB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Nc();var b=this.j;this.j=g.Rb(this.oa.Wr(a).ib);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new E3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.E_=function(){this.Ja();var a;if(a=this.j!=null)a=this.j,a=a.j.Lt(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.PD(a);var b=a.ib[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.SA()){var d=b.j.info.id,e=b.Ma,f=a.ib[0].Pe;if(this.policy.Ia){if(c=c.IK(f,e,d,3))a.D=c}else if(d=c.KA(f,e,d,3))if(c=c.JF(e),c===0)d&&(a.j=new g.yM(d));else if(c===2){this.N.start();Rgb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Mo(b.Ma)?(this.D.contains(a.ib[0].Ma)||Sgb(this,a),this.j=g.Rb(a.ib)):Rgb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(F3,g.mY);g.k=F3.prototype;g.k.Xu=function(a,b,c){var d=this;this.At();b=nhb(this,a.getId());b||(b=a.languageCode,b=this.B.isManifestless?ohb(this,b,"386"):ohb(this,b));if(b){var e=(b.index.FK(b.index.Eo())-b.index.getStartTime(b.index.Eo()))*1E3,f=this.J.U(),h=new g.gSa(f),l=function(){d.C&&d.C.reset();d.K=!0};
f.L("html5_keep_caption_data_after_seek")&&(l=null);this.C=new Qgb(h,this.J,b,function(m,n){c(m,a,n,e)},this.N||g.yG(b.info),l)}};
g.k.vT=function(){var a=this.K;this.K=!1;return a};
g.k.CB=function(a){var b=this.N?[new g.xQ({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.xQ({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.B.isManifestless?mhb(this,"386"):mhb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.lY(this.j,c.value);a()};
g.k.At=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Mx=function(){return""};
g.k.GH=function(){this.C&&(this.C.reset(),this.J.Xe("captions"))};
var X3=/^#(?:[0-9a-f]{3}){1,2}$/i;var rhb=["left","right","center","justify"];g.z(G3,g.S);g.k=G3.prototype;g.k.e5=function(a,b){this.Ya=a;this.fb=b;var c=g.Pm(this.element,this.element.parentElement);this.qb=a-c.x;this.sb=b-c.y};
g.k.d5=function(a,b){if(a!==this.Ya||b!==this.fb){g.Lp(this.element,"ytp-dragging")||g.Mp(this.element,"ytp-dragging");var c=g.Rm(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.sb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Bg(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Bg(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.Bg(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.Bg(c,0,1)*100;this.B.params.Om=b;this.B.params.Dp=c;this.B.params.Mk=
a;this.B.params.isDefault=!1;this.j.Om=b;this.j.Dp=c;this.j.Mk=a;this.j.isDefault=!1;this.qa.Om=b;this.qa.Dp=c;this.qa.Mk=a;this.qa.isDefault=!1;this.f2()}};
g.k.c5=function(){g.Op(this.element,"ytp-dragging")};
g.k.f2=function(){this.OC(this.K)};
g.k.getType=function(){return this.type};
g.k.OC=function(a){var b=this.Eb?0:Math.min(this.VY(),this.maxWidth),c=this.UY(),d=this.Eb;if(d){var e=getComputedStyle(this.D.parentNode);e=H3(e.borderLeftWidth)+H3(e.borderRightWidth)+H3(e.paddingLeft)+H3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Vi===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Fm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.PO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Mk*.96+2;h=this.j.Om;switch(h){case 0:case 3:case 6:(d=this.j.Te.fontSizeIncrement)&&d>0&&this.j.Vi!==2&&this.j.Vi!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.Dp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Fm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.PO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Fa||this.K.length>b)b=0,this.Fa=!1,this.K=[],this.N=this.Ia=this.Ka=null,g.th(this.D);for(;b<a.length;b++)whb(this,a[b])};
g.k.VY=function(){return 0};
g.k.UY=function(){return 0};
g.k.toString=function(){return g.S.prototype.toString.call(this)};yhb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
yhb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var zhb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];I3.prototype.set=function(a){this.type=a};
I3.prototype.get=function(){return this.type};
J3.prototype.clear=function(){this.state=0};
J3.prototype.update=function(){this.state=this.state===2?1:0};
J3.prototype.ye=function(){return this.state!==0};
J3.prototype.matches=function(a,b){return this.ye()&&a===this.gx&&b===this.St};
Ehb.prototype.reset=function(){this.timestamp=this.j=0};
K3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
K3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
K3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Fhb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ghb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Hhb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Ihb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Mhb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
xhb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Qhb.prototype.D=function(){};g.z(P3,g.KE);P3.prototype.toString=function(){return g.KE.prototype.toString.call(this)};g.z(Q3,g.O);Q3.prototype.jp=function(){return[]};
Q3.prototype.reset=function(){};g.z(R3,g.KE);R3.prototype.toString=function(){return g.KE.prototype.toString.call(this)};
var S3=0;g.z(T3,Q3);T3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
T3.prototype.jp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=V3(a,"b");
l!=null&&(h.bold=l);l=V3(a,"i");l!=null&&(h.italic=l);l=V3(a,"u");l!=null&&(h.underline=l);l=W3(a,"et");l!=null&&(h.charEdgeStyle=l);l=W3(a,"of");l!=null&&(h.offset=l);l=Y3(a,"bc");l!=null&&(h.background=l);l=Y3(a,"ec");l!=null&&(h.iP=l);l=Y3(a,"fc");l!=null&&(h.color=l);l=W3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=U3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=U3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=U3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=W3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.gg=l>10?l-1:l);a=W3(a,"hg");a!=null&&(h.NZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Uhb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Vhb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=Whb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!V3(m,"a");l=(U3(m,"t")||0)+l;var n=U3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.gg&&(t.gg===1?(t=r.slice(m,
m+4),t.length===4&&(u=Shb(l,n,f,h,p,t,this.pens),m+=3)):u=Shb(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var C=h,E=p,H=A.textContent?A.textContent:"",L=A.getAttribute("p");L=L?this.pens[L]:null;A=U3(A,"t")||0;u=new P3(u+A,y-A,E,t,H,C,L)}}else u=new P3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=Whb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Cib=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(Z3,Q3);Z3.prototype.reset=function(){this.B.clear()};
Z3.prototype.jp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.iP=$3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=$3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=$3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.gg=h>10?h-1:h,f.Ap=Cib.get(f.gg));e.hgHorizGroup&&(f.NZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.NB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Vi=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.LU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=$3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Mk=e.ahHorPos),e.apPoint!==void 0&&(f.Om=e.apPoint),e.avVerPos!==void 0&&(f.Dp=e.avVerPos),e.ccCols!==void 0&&(f.Vt=e.ccCols),e.rcRows!==void 0&&(f.Rs=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Xhb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+S3++,d=Xhb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.NB!=null?l.params.NB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],E;if(E=A&&A.gg===1){E=q;var H=m;if(H+3>=E.length||!E[H+1].pPenId||!E[H+2].pPenId||!E[H+3].pPenId)E=!1;else{var L=E[H+1].pPenId;(L=this.j.get(L))&&L.gg&&L.gg===2?(L=E[H+2].pPenId,L=this.j.get(L),!L||!L.gg||
L.gg<3?E=!1:(L=E[H+3].pPenId,E=(L=this.j.get(L))&&L.gg&&L.gg===2?!0:!1)):E=!1}}if(E)y=q[m+1].utf8,t=q[m+3].utf8,E=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=Rhb(u,y,E,t,H),t=new P3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var M=void 0;C=A;E=r;H=e;L=f;var W=y,V=p,ca=n,ma=[],X=g.q1("<html>"+u+"</html>");if(!X.getElementsByTagName("parsererror").length&&((M=X.firstChild)==null?0:M.childNodes.length))for(M=g.w(X.firstChild.childNodes),X=M.next();!X.done;X=M.next()){X=X.value;var Q=void 0,Y=void 0,
v=(Y=(Q=X.textContent)==null?void 0:Q.replace(/\n/g,""))!=null?Y:"";if(X.nodeType!==3||v&&v.match(/^ *$/)==null){Q={};Object.assign(Q,C||E);Y=void 0;switch((Y=X)==null?void 0:Y.tagName){case "b":Q.bold=!0;break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}ma.push(new P3(H+W,L-W,V,l.id,v,ca,Q))}}C=ma}C.length||(C=[new P3(e+y,f-y,p,l.id,u,n,A||r)])}if(C.length)for(n=g.w(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=[];return b};g.z(a4,g.mY);a4.prototype.Xu=function(a,b,c){Jgb(this.videoData.videoId,a.vssId,c)};
a4.prototype.CB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.lY(this.j,c.value);a()};g.z(b4,G3);b4.prototype.PO=function(a){var b=this.B.j;G3.prototype.PO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Dib);var e=c.j;var f=d}whb(this,c,d)}};
var Dib={x$:!0};g.z(c4,Qhb);c4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+S3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new R3(c,d-c,5,f,{textAlign:0,Om:0,Mk:b*2.5,Dp:a*5.33});e=new P3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(f4,Q3);f4.prototype.jp=function(a){a=new c4(a,a.byteLength,this.B);if(Yhb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=e4(a)*(1E3/45):a.version===1&&(a.C=e4(a)*4294967296+e4(a)),a.G=d4(a);a.G>0;a.G--){var b=d4(a),c=d4(a),d=d4(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,SX:c,TX:d,order:b.j.length}))}Dhb(this.j,a);return a.B}return[]};
f4.prototype.reset=function(){this.j.clear()};g.z(g4,G3);g.k=g4.prototype;g.k.f2=function(){g.Gp(this.Ta)};
g.k.yca=function(){g.Op(this.element,"ytp-rollup-mode");this.OC(this.Sb,!0)};
g.k.UY=function(){return this.C?this.oa:this.W};
g.k.VY=function(){return this.C?this.W:this.oa};
g.k.OC=function(a,b){this.Sb=a;if(this.B.params.Rs){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Hb=this.oa;this.W=this.oa=0;G3.prototype.OC.call(this,a);bib(this,b)}G3.prototype.OC.call(this,a)};g.z(h4,Q3);
h4.prototype.jp=function(a,b){var c=[];a=a.split(Eib);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Fib.test(e)){var h=Gib.exec(e);if(h&&h.length>=4){var l=dib(h[1]),m=dib(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.Dp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Mk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Mk=0;break;case 1:h.Mk=100;break;case 2:h.Mk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Om=q}e=e.substring(Gib.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=eib(l,m,5,t),m=new P3(l,m,5,f.id,h,!1,g.Vg(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Hib),q.length===1?(h=5,t=eib(l,m,h,t)):(p=h=6,t=Object.assign({Vt:32},t),t=new R3(l,m,p,"_"+S3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.q1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,cib(this,p,m-(p-l),h,t,r>0,y,e,c)):p=dib(n)+f}Gib.lastIndex=0}}return c};
var Fib=/^NOTE/,Eib=/(?:\r\n|\r|\n){2,}/,Gib=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Hib=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.r_.fL(h4,{jp:"wvppt"});g.z(i4,g.O);
i4.prototype.jp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a||this.Y.L("html5_use_subfragcaps_parser_for_all_live")){a:{var e=d,f=hib(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.FU;h=typeof p!=="string"?h.concat(iib(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(jib(this,p,q)):h.concat(lib(this,b,p,q))}var r=h;break a}catch(y){this.logger.j(187101178,"SS caps parsing failure fallback: "+y.message+". ");this.clear();r=null;break a}r=void 0}if(r!==
null&&r.length!==0)return r;if(this.Y.L("html5_disable_subfragcaps_fallback"))return[];r===null?(r=this.logger,g.bPa(r.tag,5,"SS caps fallback due to parse failure.",r.B)):this.logger.info("SS caps fallback due to no data received.")}a:if(a=fib(a)){try{var t=typeof a!=="string"?iib(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?jib(this,a,c):lib(this,b,a,c);break a}catch(y){if(this.Y.L("html5_report_captions_ctmp_qoe")){var u;this.J.ma("capprs",{e:(u=y)==null?void 0:u.message})}this.clear();t=[];break a}t=
void 0}else t=[];return t};
i4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
i4.prototype.reset=function(){this.j&&this.j.reset()};
i4.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var r4={windowColor:"#080808",windowOpacity:0,textAlign:2,Om:7,Mk:50,Dp:100,isDefault:!0,Te:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(j4,g.kY);g.k=j4.prototype;g.k.xa=function(){if(this.D||this.Ca){var a=this.J.Fe();a&&!a.Ja()&&a.pA()}else Bib(this,!1);g.kY.prototype.xa.call(this)};
g.k.rU=function(){return this.Y.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Ya};
g.k.Rv=function(){if(this.Ta)return this.D||this.Ca;var a=this.getAudioTrack();if(this.rU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Fgb(a,g.gQ(this.Y));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?k4(this):pib(this)||k4(this)?!0:qib(this)};
g.k.load=function(){var a=this;g.kY.prototype.load.call(this);this.Z=this.getAudioTrack();this.j?this.B&&(this.Wa.clear(),this.D?uib(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Xu(this.B,"json3",function(b,c,d,e){if(b){var f;wib(a,(f=a.B)!=null?f:void 0);a.j.vT()&&(a.Fa=[],a.J.Xe("captions"),D3(a.Ka),a.Wa.reset());if(a.videoData.Gd){var h;d=((h=d)!=null?h:0)+a.videoData.Gd}b=a.Wa.jp(b,c,d,e);if(a.fb)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Zl=a.videoData.Gd;c=!a.Y.L("html5_keep_caption_data_after_seek")&&a.Ya;a.player.bf(b,void 0,c);!a.N||a.Ca||n4(a)||!a.Y.Im||g.hE(a.Y)||g.TP(a.Y)||g.vz(a.Y)||a.Y.Ka==="shortspage"||a.player.isInline()||(g.Hp(a.Ia),b=Thb({Om:0,Mk:5,Dp:5,Rs:2,textAlign:0,Vi:0,lang:"pl"}),a.Oa=[b],c=["Kliknij ",", by przej\u015b\u0107 do ustawie\u0144"],a.qb||(e=new g.Ux(g.my()),g.P(a,e),a.qb=e.element),e=b.end-b.start,(f=g.yQ(a.B))&&a.Oa.push(new P3(b.start,e,0,b.id,f)),a.Oa.push(new P3(b.start,e,0,b.id,c[0]),new P3(b.start,
e,0,b.id,a.qb,!0),new P3(b.start,e,0,b.id,c[1],!0)),a.player.bf(a.Oa),g.Fp(a.Ia));!a.N||a.Ca||n4(a)||(g.gQ(a.Y)?p4(a,!0):q4(a,!0),a.Z&&(a.Z.D=a.B),a.player.Hp());a.N=!1}}),this.D||this.Ca||n4(this)||this.player.Dd("captionschanged",g.zQ(this.B))):(this.j=rib(this),g.P(this,this.j),this.j.CB(function(){tib(a)}))};
g.k.unload=function(){this.D&&this.B?uib(this,!1):(this.Ia&&g.Hp(this.Ia),this.player.Xe("captions"),this.Fa=[],this.j&&this.j.At(),this.Wa.clear(),this.W&&this.player.bf(this.W),this.ZU());g.kY.prototype.unload.call(this);this.player.Hp();this.player.Dd("captionschanged",{})};
g.k.create=function(){this.Rv()&&this.load();var a;a:{var b,c,d;if(this.Y.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.gda=function(){for(var a=this.J.Fe().Jb().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.$X(this.j.j,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&o4(this,b,!0)};
g.k.Jfa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);D3(this.Ka)};
g.k.onCueRangeExit=function(a){g.Yb(this.Fa,a);this.j instanceof F3&&this.j.N&&this.player.hm([a]);D3(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.gea=function(){Aib(this,this.Oa);this.Oa=null};
g.k.XU=function(){var a=this;if(!this.Eb||!this.D){this.Ka.stop();g.sea(this.Ua);this.Fa.sort(g.LE);var b=this.Fa;if(this.W){var c=g.Bn(b,function(f){return this.W.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())yib(this,c.value);b=g.w(Object.entries(this.qa));var d=b.next();for(c={};!d.done;c={fB:void 0,aq:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.fB=d;c.aq=e;this.Ua[c.fB]?(c.aq.element.parentNode||(c.aq instanceof g4||c.aq instanceof b4||g.Lg(this.qa,function(f){return function(h,l){l!==f.fB&&h.B.params.Om===f.aq.B.params.Om&&h.B.params.Mk===f.aq.B.params.Mk&&h.B.params.Dp===f.aq.B.params.Dp&&(h.dispose(),delete a.qa[l]);
return l===f.fB}}(c),this),this.K.element.appendChild(c.aq.element)),c.aq.OC(this.Ua[c.fB])):(c.aq.dispose(),delete this.qa[c.fB])}}};
g.k.nea=function(){nib(this,{},!0);this.player.Dd("captionssettingschanged")};
g.k.I9=function(){var a=r4.Te;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:r4.windowColor,windowOpacity:r4.windowOpacity};var b=Ogb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.U3=function(a,b){var c={};Object.assign(c,Ogb());Object.assign(c,a);nib(this,c,b);this.player.Dd("captionssettingschanged")};
g.k.ZU=function(){!this.D&&this.loaded&&(g.Ig(this.qa,function(a,b){a.dispose();delete this.qa[b]},this),this.XU())};
g.k.gi=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Bg(b,-2,4);this.U3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&o4(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.Y.N&&(g.gQ(this.Y)?p4(this,!!b):q4(this,!!b));break;case "track":if(!this.j)return{};if(b){this.Y.L("html5_report_caption_format_intent")&&!g.Vg(b)&&this.Xk(b.vss_id,"m");if(this.D)break;if(!g.Ta(b))break;if(g.Vg(b)){o4(this,null,!0);break}a=g.$X(this.j.j,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.yQ(e)!==b.displayName)||(c=b.translationLanguage?Hgb(e,b.translationLanguage):e)}this.EN(b.position);!c||c===this.B&&this.loaded||(b=g.VL(),a=g.AQ(c),b.length&&a===b[b.length-1]||(b.push(a),g.lt("yt-player-caption-language-preferences",b)),Ggb(this.Y)&&!this.J.isInline()&&g.lt("yt-player-caption-sticky-language",a,2592E3),o4(this,c,!0))}else return this.loaded&&this.B&&!n4(this)?g.zQ(this.B):
{};return"";case "tracklist":return this.j?g.Ql(g.$X(this.j.j,!(!b||!b.includeAsr)),function(f){return g.zQ(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||Bib(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Bib(this,!!b,b);break;case "recommendedTranslationLanguages":return g.VL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.N&&a.push("stickyLoading");return a};
g.k.Xr=function(){var a=this.B;if(this.J.SK("captions")){if(this.Y.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.rE)!=null?b:null)?{cc:g.CKa(a)}:{}}if(a)return b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.AQ(a)),{cc:b}}return{}};
g.k.wfa=function(){this.isSubtitlesOn()?(g.gQ(this.Y)?p4(this,!1):q4(this,!1),wib(this),this.Y.L("html5_report_caption_format_change")?o4(this,null,!0):(this.unload(),k4(this,!0)&&o4(this,l4(this),!1))):this.w3()};
g.k.w3=function(){var a=n4(this)||!this.B?m4(this,!0):this.B;this.Y.L("html5_report_caption_format_intent")&&a&&this.Xk(a.vssId,"m");this.isSubtitlesOn()||o4(this,n4(this)||!this.B?m4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!n4(this)};
g.k.Taa=function(){var a=n4(this);k4(this,a)?o4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.rU()&&(this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Rv()&&(a?o4(this,m4(this),!1):this.load()))};
g.k.EN=function(a){a&&(this.oa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.oa.top*100+"%",this.K.element.style.left=this.oa.left*100+"%",this.K.element.style.width=this.oa.width*100+"%",this.K.element.style.height=this.oa.height*100+"%",this.K.element.style.position="absolute",a=zib(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Dd("captionschanged",{})),this.Rv()&&this.load())};
g.k.getAudioTrack=function(){return this.fb&&this.player.getPresentingPlayerType()===2?this.videoData.jl:this.player.getAudioTrack()};
g.k.Hba=function(){var a=this.J.Fe();a&&!a.Ja()&&a.pA();this.J.isFullscreen()?(this.D=this.Ta=!0,this.loaded&&tib(this)):(this.Ta=this.Y.controlsType==="3",this.D=mib(this));o4(this,this.B)};
g.k.SN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.eb("innertubeCommand",d)};
g.k.rj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"");a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.rj(b?e:"",b?f:"",c)};
g.k.Xk=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.Xk(a,b)};
g.k.GH=function(){this.j instanceof F3&&this.j.GH()};
g.r_.fL(j4,{XU:"smucd"});g.jY("captions",j4);})(_yt_player);
